// GENERATED CODE - DO NOT EDIT.
// This file was generated by Binary Message Schema (BMS).
// Manual changes will be overwritten the next time code is generated.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <vector>
#include "acme/telemetry/Header.hpp"

namespace acme {
namespace telemetry {
namespace packet {

struct Packet {
  ::acme::telemetry::Header header{};
  std::uint32_t payloadLength{};

  /**
   * Encodes this message instance into wire bytes.
   *
   * @return encoded bytes in deterministic field order
   */
  std::vector<std::uint8_t> encode() const;

  /**
   * Decodes one full message from wire bytes.
   *
   * @param data encoded message bytes
   * @return decoded message value
   */
  static Packet decode(std::span<const std::uint8_t> data);

  /**
   * Decodes one message from the current cursor position.
   *
   * @param data encoded message bytes
   * @param cursor current decode cursor; advanced past this message
   * @return decoded message value
   */
  static Packet decodeFrom(std::span<const std::uint8_t> data, std::size_t& cursor);
};

}  // namespace packet
}  // namespace telemetry
}  // namespace acme
