// GENERATED CODE - DO NOT EDIT.
// This file was generated by Binary Message Schema (BMS).
// Manual changes will be overwritten the next time code is generated.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <vector>

namespace acme {
namespace telemetry {
namespace conditional {
namespace relational {

struct ConditionalRelationalFrame {
  std::uint8_t version{};
  std::uint8_t ltMode{};
  std::uint8_t lteMode{};
  std::uint8_t gtMode{};
  std::uint8_t gteMode{};
  std::uint8_t betweenMode{};
  std::uint8_t compoundMode{};

  /**
   * Encodes this message instance into wire bytes.
   *
   * @return encoded bytes in deterministic field order
   */
  std::vector<std::uint8_t> encode() const;

  /**
   * Decodes one full message from wire bytes.
   *
   * @param data encoded message bytes
   * @return decoded message value
   */
  static ConditionalRelationalFrame decode(std::span<const std::uint8_t> data);

  /**
   * Decodes one message from the current cursor position.
   *
   * @param data encoded message bytes
   * @param cursor current decode cursor; advanced past this message
   * @return decoded message value
   */
  static ConditionalRelationalFrame decodeFrom(std::span<const std::uint8_t> data, std::size_t& cursor);
};

}  // namespace relational
}  // namespace conditional
}  // namespace telemetry
}  // namespace acme
