package io.github.sportne.bms.codegen.java;

import io.github.sportne.bms.codegen.common.SchemaIndex;
import io.github.sportne.bms.model.resolved.ResolvedArray;
import io.github.sportne.bms.model.resolved.ResolvedBlobArray;
import io.github.sportne.bms.model.resolved.ResolvedBlobVector;
import io.github.sportne.bms.model.resolved.ResolvedFloat;
import io.github.sportne.bms.model.resolved.ResolvedMessageMember;
import io.github.sportne.bms.model.resolved.ResolvedMessageType;
import io.github.sportne.bms.model.resolved.ResolvedScaledInt;
import io.github.sportne.bms.model.resolved.ResolvedSchema;
import io.github.sportne.bms.model.resolved.ResolvedVarString;
import io.github.sportne.bms.model.resolved.ResolvedVector;
import io.github.sportne.bms.util.BmsException;
import io.github.sportne.bms.util.Diagnostic;
import io.github.sportne.bms.util.DiagnosticSeverity;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * Generates Java source files from the resolved model.
 *
 * <p>Each message type becomes one Java class with deterministic field declarations plus
 * encode/decode logic. This generator currently supports foundation, numeric, collection, and
 * conditional members.
 */
public final class JavaCodeGenerator {
  private static final String GENERATED_FILE_BANNER =
      """
      /**
       * GENERATED CODE - DO NOT EDIT.
       *
       * This file was generated by Binary Message Schema (BMS).
       * Manual changes will be overwritten the next time code is generated.
       */
      """;

  private static final String SHARED_IO_HELPERS =
      """
      /**
       * Writes one signed 8-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       */
      private static void writeInt8(ByteArrayOutputStream out, byte value) {
        out.write(value);
      }

      /**
       * Writes one unsigned 8-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       */
      private static void writeUInt8(ByteArrayOutputStream out, short value) {
        out.write(value & 0xFF);
      }

      /**
       * Writes one signed 16-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       * @param order byte order to use
       */
      private static void writeInt16(ByteArrayOutputStream out, short value, ByteOrder order) {
        ByteBuffer buffer = ByteBuffer.allocate(Short.BYTES).order(order);
        buffer.putShort(value);
        out.write(buffer.array(), 0, Short.BYTES);
      }

      /**
       * Writes one unsigned 16-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       * @param order byte order to use
       */
      private static void writeUInt16(ByteArrayOutputStream out, int value, ByteOrder order) {
        writeInt16(out, (short) (value & 0xFFFF), order);
      }

      /**
       * Writes one signed 32-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       * @param order byte order to use
       */
      private static void writeInt32(ByteArrayOutputStream out, int value, ByteOrder order) {
        ByteBuffer buffer = ByteBuffer.allocate(Integer.BYTES).order(order);
        buffer.putInt(value);
        out.write(buffer.array(), 0, Integer.BYTES);
      }

      /**
       * Writes one unsigned 32-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       * @param order byte order to use
       */
      private static void writeUInt32(ByteArrayOutputStream out, long value, ByteOrder order) {
        writeInt32(out, (int) (value & 0xFFFFFFFFL), order);
      }

      /**
       * Writes one signed 64-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       * @param order byte order to use
       */
      private static void writeInt64(ByteArrayOutputStream out, long value, ByteOrder order) {
        ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES).order(order);
        buffer.putLong(value);
        out.write(buffer.array(), 0, Long.BYTES);
      }

      /**
       * Writes one unsigned 64-bit value.
       *
       * @param out destination byte stream
       * @param value value to write
       * @param order byte order to use
       */
      private static void writeUInt64(ByteArrayOutputStream out, long value, ByteOrder order) {
        writeInt64(out, value, order);
      }

      /**
       * Reads one signed 8-bit value.
       *
       * @param input source byte buffer
       * @return decoded value
       */
      private static byte readInt8(ByteBuffer input) {
        return input.get();
      }

      /**
       * Reads one unsigned 8-bit value.
       *
       * @param input source byte buffer
       * @return decoded value
       */
      private static short readUInt8(ByteBuffer input) {
        return (short) (input.get() & 0xFF);
      }

      /**
       * Reads one signed 16-bit value.
       *
       * @param input source byte buffer
       * @param order byte order to use
       * @return decoded value
       */
      private static short readInt16(ByteBuffer input, ByteOrder order) {
        ByteBuffer slice = input.slice().order(order);
        short value = slice.getShort();
        input.position(input.position() + Short.BYTES);
        return value;
      }

      /**
       * Reads one unsigned 16-bit value.
       *
       * @param input source byte buffer
       * @param order byte order to use
       * @return decoded value
       */
      private static int readUInt16(ByteBuffer input, ByteOrder order) {
        return Short.toUnsignedInt(readInt16(input, order));
      }

      /**
       * Reads one signed 32-bit value.
       *
       * @param input source byte buffer
       * @param order byte order to use
       * @return decoded value
       */
      private static int readInt32(ByteBuffer input, ByteOrder order) {
        ByteBuffer slice = input.slice().order(order);
        int value = slice.getInt();
        input.position(input.position() + Integer.BYTES);
        return value;
      }

      /**
       * Reads one unsigned 32-bit value.
       *
       * @param input source byte buffer
       * @param order byte order to use
       * @return decoded value
       */
      private static long readUInt32(ByteBuffer input, ByteOrder order) {
        return Integer.toUnsignedLong(readInt32(input, order));
      }

      /**
       * Reads one signed 64-bit value.
       *
       * @param input source byte buffer
       * @param order byte order to use
       * @return decoded value
       */
      private static long readInt64(ByteBuffer input, ByteOrder order) {
        ByteBuffer slice = input.slice().order(order);
        long value = slice.getLong();
        input.position(input.position() + Long.BYTES);
        return value;
      }

      /**
       * Reads one unsigned 64-bit value.
       *
       * @param input source byte buffer
       * @param order byte order to use
       * @return decoded value
       */
      private static long readUInt64(ByteBuffer input, ByteOrder order) {
        return readInt64(input, order);
      }

      /**
       * Validates a collection count value and converts it to an int.
       *
       * @param countValue decoded count value as long
       * @param fieldName field name shown in exception text
       * @return validated count value as int
       */
      private static int requireCount(long countValue, String fieldName) {
        if (countValue < 0 || countValue > Integer.MAX_VALUE) {
          throw new IllegalArgumentException(
              "Count field " + fieldName + " must be between 0 and Integer.MAX_VALUE.");
        }
        return (int) countValue;
      }

      /**
       * Validates an unsigned-64 count and converts it to an int.
       *
       * @param countValue raw unsigned-64 count bits
       * @param fieldName field name shown in exception text
       * @return validated count value as int
       */
      private static int requireCountUnsignedLong(long countValue, String fieldName) {
        if (Long.compareUnsigned(countValue, Integer.toUnsignedLong(Integer.MAX_VALUE)) > 0) {
          throw new IllegalArgumentException(
              "Unsigned count field "
                  + fieldName
                  + " must be <= Integer.MAX_VALUE. Received "
                  + Long.toUnsignedString(countValue)
                  + '.');
        }
        return (int) countValue;
      }

      /**
       * Converts a scaled logical value to a signed integer raw value.
       *
       * @param logicalValue logical floating-point value
       * @param scale scaling factor from the schema
       * @param minInclusive signed minimum raw value
       * @param maxInclusive signed maximum raw value
       * @param fieldName field/member name for exception text
       * @return rounded raw integer value
       */
      private static long scaleToSignedRaw(
          double logicalValue,
          double scale,
          long minInclusive,
          long maxInclusive,
          String fieldName) {
        if (!Double.isFinite(logicalValue)) {
          throw new IllegalArgumentException("Non-finite value for " + fieldName + '.');
        }
        if (scale == 0.0d || !Double.isFinite(scale)) {
          throw new IllegalArgumentException("Invalid scale for " + fieldName + '.');
        }

        double rawValue = logicalValue / scale;
        if (!Double.isFinite(rawValue)) {
          throw new IllegalArgumentException("Scaled value is not finite for " + fieldName + '.');
        }

        if (rawValue < minInclusive || rawValue > maxInclusive) {
          throw new IllegalArgumentException(
              "Value " + logicalValue + " is outside raw range for " + fieldName + '.');
        }

        long rounded = Math.round(rawValue);
        if (rounded < minInclusive || rounded > maxInclusive) {
          throw new IllegalArgumentException(
              "Rounded value for " + fieldName + " is outside raw range.");
        }
        return rounded;
      }

      /**
       * Converts a scaled logical value to an unsigned integer raw value.
       *
       * @param logicalValue logical floating-point value
       * @param scale scaling factor from the schema
       * @param maxInclusive unsigned maximum raw value that fits in a signed long
       * @param fieldName field/member name for exception text
       * @return rounded raw integer value
       */
      private static long scaleToUnsignedRaw(
          double logicalValue, double scale, long maxInclusive, String fieldName) {
        if (!Double.isFinite(logicalValue)) {
          throw new IllegalArgumentException("Non-finite value for " + fieldName + '.');
        }
        if (scale == 0.0d || !Double.isFinite(scale)) {
          throw new IllegalArgumentException("Invalid scale for " + fieldName + '.');
        }

        double rawValue = logicalValue / scale;
        if (!Double.isFinite(rawValue)) {
          throw new IllegalArgumentException("Scaled value is not finite for " + fieldName + '.');
        }
        if (rawValue < 0.0d || rawValue > maxInclusive) {
          throw new IllegalArgumentException(
              "Value " + logicalValue + " is outside unsigned raw range for " + fieldName + '.');
        }

        long rounded = Math.round(rawValue);
        if (rounded < 0 || rounded > maxInclusive) {
          throw new IllegalArgumentException(
              "Rounded value for " + fieldName + " is outside unsigned raw range.");
        }
        return rounded;
      }

      /**
       * Converts a scaled logical value to one unsigned 64-bit raw value.
       *
       * <p>The returned {@code long} stores the same 64 raw bits as the wire value.
       *
       * @param logicalValue logical floating-point value
       * @param scale scaling factor from the schema
       * @param fieldName field/member name for exception text
       * @return rounded raw unsigned-64 value encoded in one long
       */
      private static long scaleToUnsignedRaw64(double logicalValue, double scale, String fieldName) {
        if (!Double.isFinite(logicalValue)) {
          throw new IllegalArgumentException("Non-finite value for " + fieldName + '.');
        }
        if (scale == 0.0d || !Double.isFinite(scale)) {
          throw new IllegalArgumentException("Invalid scale for " + fieldName + '.');
        }

        double rawValue = logicalValue / scale;
        if (!Double.isFinite(rawValue)) {
          throw new IllegalArgumentException("Scaled value is not finite for " + fieldName + '.');
        }
        if (rawValue < 0.0d) {
          throw new IllegalArgumentException(
              "Value " + logicalValue + " is outside unsigned raw range for " + fieldName + '.');
        }

        java.math.BigDecimal roundedDecimal =
            java.math.BigDecimal.valueOf(rawValue).setScale(0, java.math.RoundingMode.HALF_UP);
        java.math.BigInteger roundedInteger;
        try {
          roundedInteger = roundedDecimal.toBigIntegerExact();
        } catch (ArithmeticException exception) {
          throw new IllegalArgumentException(
              "Rounded value for " + fieldName + " is outside unsigned raw range.");
        }

        java.math.BigInteger maxUnsigned = new java.math.BigInteger("18446744073709551615");
        if (roundedInteger.signum() < 0 || roundedInteger.compareTo(maxUnsigned) > 0) {
          throw new IllegalArgumentException(
              "Rounded value for " + fieldName + " is outside unsigned raw range.");
        }
        return roundedInteger.longValue();
      }

      /**
       * Converts one unsigned 64-bit raw value stored in a {@code long} to a {@code double}.
       *
       * @param value raw unsigned-64 value bits
       * @return floating-point value in the unsigned-64 numeric range
       */
      private static double unsignedLongToDouble(long value) {
        if (value >= 0L) {
          return (double) value;
        }
        return ((double) (value & Long.MAX_VALUE)) + 0x1.0p63;
      }
      """
          .indent(2)
          .replace("private static ", "static ")
          .replace("  \n", "\n");

  private static final String CHECKSUM_IO_HELPERS =
      """
      /**
       * Validates one checksum byte range against available source length.
       *
       * @param availableLength available byte count in the source
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @param algorithm checksum algorithm name
       * @param rangeText original range text used in exception messages
       */
      private static void validateChecksumRange(
          int availableLength,
          int rangeStart,
          int rangeEnd,
          String algorithm,
          String rangeText) {
        if (rangeStart < 0 || rangeEnd < rangeStart || rangeEnd >= availableLength) {
          throw new IllegalArgumentException(
              "Checksum "
                  + algorithm
                  + " range "
                  + rangeText
                  + " is out of bounds for "
                  + availableLength
                  + " available bytes.");
        }
      }

      /**
       * Computes CRC-16/CCITT-FALSE over one byte-array range.
       *
       * @param source source bytes
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 16-bit checksum value
       */
      private static int crc16(byte[] source, int rangeStart, int rangeEnd) {
        int crc = 0xFFFF;
        for (int index = rangeStart; index <= rangeEnd; index++) {
          crc ^= (source[index] & 0xFF) << 8;
          for (int bit = 0; bit < 8; bit++) {
            if ((crc & 0x8000) != 0) {
              crc = ((crc << 1) ^ 0x1021) & 0xFFFF;
            } else {
              crc = (crc << 1) & 0xFFFF;
            }
          }
        }
        return crc & 0xFFFF;
      }

      /**
       * Computes CRC-32 over one byte-array range.
       *
       * @param source source bytes
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 32-bit checksum value
       */
      private static long crc32(byte[] source, int rangeStart, int rangeEnd) {
        CRC32 crc32 = new CRC32();
        for (int index = rangeStart; index <= rangeEnd; index++) {
          crc32.update(source[index] & 0xFF);
        }
        return crc32.getValue();
      }

      /**
       * Computes CRC-64/ECMA-182 over one byte-array range.
       *
       * @param source source bytes
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 64-bit checksum value
       */
      private static long crc64(byte[] source, int rangeStart, int rangeEnd) {
        long crc = 0L;
        for (int index = rangeStart; index <= rangeEnd; index++) {
          crc ^= (source[index] & 0xFFL) << 56;
          for (int bit = 0; bit < 8; bit++) {
            if ((crc & 0x8000000000000000L) != 0L) {
              crc = (crc << 1) ^ 0x42F0E1EBA9EA3693L;
            } else {
              crc = crc << 1;
            }
          }
        }
        return crc;
      }

      /**
       * Computes SHA-256 over one byte-array range.
       *
       * @param source source bytes
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 32-byte digest value
       */
      private static byte[] sha256(byte[] source, int rangeStart, int rangeEnd) {
        try {
          java.security.MessageDigest digest =
              java.security.MessageDigest.getInstance("SHA-256");
          digest.update(source, rangeStart, (rangeEnd - rangeStart) + 1);
          return digest.digest();
        } catch (java.security.NoSuchAlgorithmException exception) {
          throw new IllegalStateException(
              "SHA-256 digest is not available in this JDK.", exception);
        }
      }

      /**
       * Computes CRC-16/CCITT-FALSE over one byte-buffer range.
       *
       * @param input source byte buffer
       * @param messageStartPosition start index of the decoded message
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 16-bit checksum value
       */
      private static int crc16(
          ByteBuffer input, int messageStartPosition, int rangeStart, int rangeEnd) {
        int absoluteStart = messageStartPosition + rangeStart;
        int absoluteEnd = messageStartPosition + rangeEnd;
        int crc = 0xFFFF;
        for (int index = absoluteStart; index <= absoluteEnd; index++) {
          crc ^= (input.get(index) & 0xFF) << 8;
          for (int bit = 0; bit < 8; bit++) {
            if ((crc & 0x8000) != 0) {
              crc = ((crc << 1) ^ 0x1021) & 0xFFFF;
            } else {
              crc = (crc << 1) & 0xFFFF;
            }
          }
        }
        return crc & 0xFFFF;
      }

      /**
       * Computes CRC-32 over one byte-buffer range.
       *
       * @param input source byte buffer
       * @param messageStartPosition start index of the decoded message
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 32-bit checksum value
       */
      private static long crc32(
          ByteBuffer input, int messageStartPosition, int rangeStart, int rangeEnd) {
        int absoluteStart = messageStartPosition + rangeStart;
        int absoluteEnd = messageStartPosition + rangeEnd;
        CRC32 crc32 = new CRC32();
        for (int index = absoluteStart; index <= absoluteEnd; index++) {
          crc32.update(input.get(index) & 0xFF);
        }
        return crc32.getValue();
      }

      /**
       * Computes CRC-64/ECMA-182 over one byte-buffer range.
       *
       * @param input source byte buffer
       * @param messageStartPosition start index of the decoded message
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 64-bit checksum value
       */
      private static long crc64(
          ByteBuffer input, int messageStartPosition, int rangeStart, int rangeEnd) {
        int absoluteStart = messageStartPosition + rangeStart;
        int absoluteEnd = messageStartPosition + rangeEnd;
        long crc = 0L;
        for (int index = absoluteStart; index <= absoluteEnd; index++) {
          crc ^= (input.get(index) & 0xFFL) << 56;
          for (int bit = 0; bit < 8; bit++) {
            if ((crc & 0x8000000000000000L) != 0L) {
              crc = (crc << 1) ^ 0x42F0E1EBA9EA3693L;
            } else {
              crc = crc << 1;
            }
          }
        }
        return crc;
      }

      /**
       * Computes SHA-256 over one byte-buffer range.
       *
       * @param input source byte buffer
       * @param messageStartPosition start index of the decoded message
       * @param rangeStart first checksum byte index (inclusive)
       * @param rangeEnd last checksum byte index (inclusive)
       * @return computed 32-byte digest value
       */
      private static byte[] sha256(
          ByteBuffer input, int messageStartPosition, int rangeStart, int rangeEnd) {
        int absoluteStart = messageStartPosition + rangeStart;
        int absoluteEnd = messageStartPosition + rangeEnd;
        try {
          java.security.MessageDigest digest =
              java.security.MessageDigest.getInstance("SHA-256");
          ByteBuffer slice = input.duplicate();
          slice.position(absoluteStart);
          slice.limit(absoluteEnd + 1);
          digest.update(slice);
          return digest.digest();
        } catch (java.security.NoSuchAlgorithmException exception) {
          throw new IllegalStateException(
              "SHA-256 digest is not available in this JDK.", exception);
        }
      }
      """
          .indent(2)
          .replace("private static ", "static ")
          .replace("  \n", "\n");

  /**
   * Writes generated Java files into the provided output directory.
   *
   * @param schema resolved schema to generate from
   * @param outputDirectory target directory for generated Java files
   * @throws BmsException if generation fails
   */
  public void generate(ResolvedSchema schema, Path outputDirectory) throws BmsException {
    GenerationContext generationContext = buildGenerationContext(schema);

    for (ResolvedMessageType messageType : schema.messageTypes()) {
      Path packageDirectory =
          outputDirectory.resolve(messageType.effectiveNamespace().replace('.', '/'));
      Path outputPath = packageDirectory.resolve(messageType.name() + ".java");

      ensureSupportedMembers(messageType, generationContext, outputPath);

      String source = renderMessageType(messageType, generationContext);
      try {
        Files.createDirectories(packageDirectory);
        Files.writeString(outputPath, source, StandardCharsets.UTF_8);
      } catch (IOException exception) {
        Diagnostic diagnostic =
            new Diagnostic(
                DiagnosticSeverity.ERROR,
                "GENERATOR_JAVA_IO_ERROR",
                "Failed to write Java source: " + exception.getMessage(),
                outputPath.toString(),
                -1,
                -1);
        throw new BmsException("Java code generation failed.", List.of(diagnostic));
      }
    }
  }

  /**
   * Builds lookup maps used during Java generation.
   *
   * @param schema resolved schema used for generation
   * @return generation context with deterministic lookup maps
   */
  private static GenerationContext buildGenerationContext(ResolvedSchema schema) {
    return GenerationContext.fromSchemaIndex(SchemaIndex.fromResolvedSchema(schema));
  }

  /**
   * Verifies that this generator supports every member and type used by the message.
   *
   * @param messageType message being generated
   * @param generationContext reusable lookup maps used for validation
   * @param outputPath output file path used in diagnostics
   * @throws BmsException if unsupported members or references are found
   */
  private static void ensureSupportedMembers(
      ResolvedMessageType messageType, GenerationContext generationContext, Path outputPath)
      throws BmsException {
    JavaSupportChecker.ensureSupportedMembers(messageType, generationContext, outputPath);
  }

  /**
   * Renders one complete Java class source file.
   *
   * @param messageType message type to render
   * @param generationContext reusable lookup maps
   * @return generated Java source text
   */
  private static String renderMessageType(
      ResolvedMessageType messageType, GenerationContext generationContext) {
    StringBuilder builder = new StringBuilder();

    builder.append(GENERATED_FILE_BANNER).append('\n');
    builder.append("package ").append(messageType.effectiveNamespace()).append(";\n\n");
    appendImports(builder, messageType, generationContext);

    builder.append("public final class ").append(messageType.name()).append(" {\n");

    appendMemberDeclarations(builder, messageType, generationContext);
    appendBitFieldHelpers(builder, messageType);
    JavaEncodeEmitter.appendEncodeMethod(builder, messageType, generationContext);
    JavaDecodeEmitter.appendDecodeMethods(builder, messageType, generationContext);

    builder.append(SHARED_IO_HELPERS);
    if (containsChecksumMember(messageType.members())) {
      builder.append(CHECKSUM_IO_HELPERS);
    }
    builder.append("}\n");

    return builder.toString();
  }

  /**
   * Appends import lines required by one generated message class.
   *
   * @param builder destination source builder
   * @param messageType message being rendered
   * @param generationContext reusable lookup maps
   */
  private static void appendImports(
      StringBuilder builder, ResolvedMessageType messageType, GenerationContext generationContext) {
    JavaHelperEmitter.appendImports(builder, messageType, generationContext);
  }

  /**
   * Returns whether one member list contains a checksum member recursively.
   *
   * @param members members to inspect
   * @return {@code true} when at least one checksum member is present
   */
  private static boolean containsChecksumMember(List<ResolvedMessageMember> members) {
    return JavaHelperEmitter.containsChecksumMember(members);
  }

  /**
   * Appends field declarations for message members.
   *
   * @param builder destination source builder
   * @param messageType message being rendered
   * @param generationContext reusable lookup maps
   */
  private static void appendMemberDeclarations(
      StringBuilder builder, ResolvedMessageType messageType, GenerationContext generationContext) {
    JavaDeclarationEmitter.appendMemberDeclarations(builder, messageType, generationContext);
  }

  /**
   * Appends helper methods for each bitField member.
   *
   * @param builder destination source builder
   * @param messageType message being rendered
   */
  private static void appendBitFieldHelpers(
      StringBuilder builder, ResolvedMessageType messageType) {
    JavaHelperEmitter.appendBitFieldHelpers(builder, messageType);
  }

  static record GenerationContext(
      Map<String, ResolvedMessageType> messageTypeByName,
      Map<String, ResolvedFloat> reusableFloatByName,
      Map<String, ResolvedScaledInt> reusableScaledIntByName,
      Map<String, ResolvedArray> reusableArrayByName,
      Map<String, ResolvedVector> reusableVectorByName,
      Map<String, ResolvedBlobArray> reusableBlobArrayByName,
      Map<String, ResolvedBlobVector> reusableBlobVectorByName,
      Map<String, ResolvedVarString> reusableVarStringByName) {
    /**
     * Creates one generation context from a shared schema index.
     *
     * @param schemaIndex shared schema index
     * @return generation context used by Java code generation
     */
    static GenerationContext fromSchemaIndex(SchemaIndex schemaIndex) {
      return new GenerationContext(
          schemaIndex.messageTypeByName(),
          schemaIndex.reusableFloatByName(),
          schemaIndex.reusableScaledIntByName(),
          schemaIndex.reusableArrayByName(),
          schemaIndex.reusableVectorByName(),
          schemaIndex.reusableBlobArrayByName(),
          schemaIndex.reusableBlobVectorByName(),
          schemaIndex.reusableVarStringByName());
    }
  }
}
