/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.sportne.bms;

import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import org.junit.Test;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }

  @Test
  public void mainPrintsGreeting() {
    ByteArrayOutputStream output = new ByteArrayOutputStream();
    PrintStream originalOut = System.out;

    try {
      System.setOut(new PrintStream(output, false, StandardCharsets.UTF_8));
      App.main(new String[0]);
    } finally {
      System.setOut(originalOut);
    }

    assertTrue(output.toString(StandardCharsets.UTF_8).contains("Hello World!"));
  }
}
